<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_INFORMASI UMUM_src-components-core-Chec_797067</name>
   <tag></tag>
   <elementGuidId>e9fa1045-e6e5-42e8-ab16-616577d07fe7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>src-components-core-Checkbox-Checkbox-module__control-indicator--2Za36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentMain&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box__body&quot;]/div[3]/div[@class=&quot;centered-container&quot;]/div[@class=&quot;acceptance-line&quot;]/div[@class=&quot;src-components-core-Checkbox-Checkbox-module__Checkbox--2lqWj check-button&quot;]/label[@class=&quot;src-components-core-Checkbox-Checkbox-module__control--Zcb_a src-components-core-Checkbox-Checkbox-module__control-checkbox--2ALl4&quot;]/div[@class=&quot;src-components-core-Checkbox-Checkbox-module__control-indicator--2Za36&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='ContentMain']/div/div[3]/div/div[3]/div[2]/div/div/label/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
   </webElementXpaths>
</WebElementEntity>
